export {default as Post} from "./post/Post" 
export {default as Upload} from "./upload/Upload"
export {default as Login} from "./auth/Login"
export {default as Register} from "./auth/Register"
export {default as Reset} from "./auth/Reset"